name: Homebrew Bump
on:
  push:
    tags:
      - 'html-query-v*'

jobs:
  homebrew:
    name: Bump Homebrew formula
    runs-on: ubuntu-latest
    steps:
      - name: Extract version
        id: extract-version
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/html-query-}" >> "$GITHUB_OUTPUT"
      - uses: mislav/bump-homebrew-formula-action@v3
        with:
          formula-name: hq
          commit-message: |
            hq ${{ steps.extract-version.outputs.VERSION }}

            Created by https://github.com/mislav/bump-homebrew-formula-action
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
